LIBSNDFILE = ~/source/learning/libsndfile/libsndfile-1.0.26

# delete sproc or sprocsine before compilation, depending on which one is needed
sproc: sproc.o DelayEffect.o DelayLine.o
	/bin/bash $(LIBSNDFILE)/libtool --mode=link g++  -g -O2 -W -Wall -pedantic -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wshadow -pipe -o sproc  sproc.o DelayEffect.o DelayLine.o $(LIBSNDFILE)/src/libsndfile.la -lm

sprocsine: sprocsine.o MakeSine.o
	/bin/bash $(LIBSNDFILE)/libtool --mode=link g++  -g -O2 -W -Wall -pedantic -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wshadow -pipe -o sprocsine  sprocsine.o MakeSine.o $(LIBSNDFILE)/src/libsndfile.la -lm

sproc.o: sproc.cp
	g++ -DHAVE_CONFIG_H -I. -I. -I$(LIBSNDFILE)/src -I./$(LIBSNDFILE)/src -g -O2 -W -Wall -pedantic -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wshadow -pipe -c sproc.cp

sprocsine.o: sprocsine.cp
	g++ -DHAVE_CONFIG_H -I. -I. -I$(LIBSNDFILE)/src -I./$(LIBSNDFILE)/src -g -O2 -W -Wall -pedantic -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wshadow -pipe -c sprocsine.cp  

DelayEffect.o: DelayEffect.cp
	g++ -DHAVE_CONFIG_H -I. -I. -I$(LIBSNDFILE)/src -I./../src -g -O2 -pipe -c DelayEffect.cp

DelayLine.o: DelayLine.cp
	g++ -DHAVE_CONFIG_H -I. -I. -I$(LIBSNDFILE)/src -I./../src -g -O2 -pipe -c DelayLine.cp

MakeSine.o: MakeSine.cp
	g++ -DHAVE_CONFIG_H -I. -I. -I$(LIBSNDFILE)/src -I./../src -g -O2 -pipe -c MakeSine.cp